"""Quiz bank. Each item:
  id, module, type (mcq|tf|short|applied), difficulty (1 recall | 2 apply | 3 judgement),
  q, options (mcq only), answer, rationale
"""

QUIZ = [
# ---------- recall / MCQ ----------
dict(id="Q01", module="m2", type="mcq", difficulty=1,
     q="Which fields are REQUIRED in a skill's YAML frontmatter?",
     options=["name and version", "name and description", "description and allowed-tools", "name, description and license"],
     answer="name and description",
     rationale="Only `name` and `description` are required by the specification. `license`, `compatibility`, `metadata` and `allowed-tools` are optional, and `allowed-tools` is still experimental."),

dict(id="Q02", module="m2", type="mcq", difficulty=1,
     q="What is the maximum length of a skill's `name`?",
     options=["32 characters", "64 characters", "128 characters", "1,024 characters"],
     answer="64 characters",
     rationale="`name` is capped at 64 characters; `description` at 1,024; `compatibility` at 500."),

dict(id="Q03", module="m3", type="mcq", difficulty=1,
     q="At session start, what is loaded into context for every installed skill?",
     options=["The entire skill folder", "The SKILL.md body", "Only name and description", "Nothing until the skill is named by the user"],
     answer="Only name and description",
     rationale="Tier 1 of progressive disclosure is metadata only, roughly 100 tokens per skill. The body loads at tier 2, when the description matches."),

dict(id="Q04", module="m3", type="mcq", difficulty=2,
     q="Why is putting deterministic logic in `scripts/` cheaper than putting it in `references/`?",
     options=["Scripts are compressed before loading", "Script source is never tokenised — only its output enters context", "Reference files are always loaded at startup", "Scripts run on a separate model"],
     answer="Script source is never tokenised — only its output enters context",
     rationale="A 600-line script can cost a few dozen tokens of stdout. A reference file costs its full length the moment it is read."),

dict(id="Q05", module="m5", type="mcq", difficulty=1,
     q="Which set of skills is built into Claude.ai and cannot be toggled off?",
     options=["skill-creator and mcp-builder", "docx, pdf, pptx, xlsx", "brand-guidelines and canvas-design", "webapp-testing and frontend-design"],
     answer="docx, pdf, pptx, xlsx",
     rationale="The four document skills are built in and always available in Claude.ai/Desktop. Example skills are toggleable and off by default, except skill-creator."),

dict(id="Q06", module="m5", type="mcq", difficulty=1,
     q="Which example skill is enabled by default in Claude?",
     options=["mcp-builder", "skill-creator", "algorithmic-art", "webapp-testing"],
     answer="skill-creator",
     rationale="skill-creator is the documented exception to the example skills being off by default."),

dict(id="Q07", module="m7", type="mcq", difficulty=1,
     q="Which tool is a hard requirement for using skills on the Claude Messages API?",
     options=["The web search tool", "The code execution tool", "The computer use tool", "The text editor tool"],
     answer="The code execution tool",
     rationale="Skills need a filesystem and a shell. On the API those come from the code execution tool's container; without it the request fails with a 400."),

dict(id="Q08", module="m7", type="mcq", difficulty=1,
     q="Where do uploaded custom skills mount inside the API execution container?",
     options=["/home/claude/skills/", "/skills/<skill-name>/", "/mnt/skills/custom/", "/tmp/skills/"],
     answer="/skills/<skill-name>/",
     rationale="Both custom and built-in skills are mounted under /skills/, which is why traces show `cat /skills/<name>/SKILL.md`."),

dict(id="Q09", module="m7", type="mcq", difficulty=2,
     q="A script inside your skill does `pip install statsmodels` at runtime and fails on the API. Why?",
     options=["pip is not installed in the container", "The container has no internet connection", "Skills are not allowed to run pip", "The package is blocked by policy"],
     answer="The container has no internet connection",
     rationale="The API sandbox has no network access, so every dependency must already be present. Claude.ai and Desktop containers do have network access, which is why the same script can pass there and fail on the API."),

dict(id="Q10", module="m8", type="mcq", difficulty=1,
     q="Where do project-scoped skills live in a Claude Code repository?",
     options=[".skills/<name>/SKILL.md", ".claude/skills/<name>/SKILL.md", "skills/<name>/skill.md", "~/.claude/project-skills/"],
     answer=".claude/skills/<name>/SKILL.md",
     rationale="Project skills go in `.claude/skills/`; personal skills in `~/.claude/skills/`."),

dict(id="Q11", module="m8", type="mcq", difficulty=2,
     q="You add a new skill folder to `.claude/skills/` and `/skills` does not list it. Most likely cause?",
     options=["The frontmatter is invalid", "Claude Code needs restarting to discover it", "The skill exceeds 500 lines", "Project skills must be registered in settings.json"],
     answer="Claude Code needs restarting to discover it",
     rationale="Skills are discovered at startup. Invalid frontmatter is the other candidate, but the restart is the documented and far more common cause."),

dict(id="Q12", module="m9", type="mcq", difficulty=2,
     q="In the Agent SDK you set `allowed_tools=[\"Skill\", \"Task\", \"Bash\"]` and your skills still never load. What is missing?",
     options=["`skills=\"all\"` in the options", "`setting_sources` including 'project' or 'user'", "The Read tool", "A beta header"],
     answer="`setting_sources` including 'project' or 'user'",
     rationale="Skills in the SDK need both the `Skill` tool AND `setting_sources` naming where to load from. Omitting `setting_sources` loads nothing, silently."),

dict(id="Q13", module="m9", type="mcq", difficulty=1,
     q="Which tool must be allowed for the main agent to dispatch subagents?",
     options=["Agent", "Dispatch", "Task", "Subagent"],
     answer="Task",
     rationale="`Task` is the dispatch tool. Without it, declared agents can never be invoked."),

dict(id="Q14", module="m9", type="mcq", difficulty=1,
     q="Which tools are permitted by default in the Agent SDK without explicit granting?",
     options=["Read, Grep, Glob", "Read, Write, Bash", "All tools", "None"],
     answer="Read, Grep, Glob",
     rationale="Read-only tools are default-allowed. Write, Bash, WebSearch and WebFetch must be granted explicitly."),

dict(id="Q15", module="m4", type="mcq", difficulty=2,
     q="Which statement about context cost is correct?",
     options=["Tool definitions load on demand; skills are always in context",
              "Tool definitions are always in context; skills load progressively",
              "Both load progressively",
              "Both are always fully loaded"],
     answer="Tool definitions are always in context; skills load progressively",
     rationale="This asymmetry is why a skill bundling a rarely used script can be cheaper than exposing the same capability as a permanent tool."),

dict(id="Q16", module="m4", type="mcq", difficulty=2,
     q="Five teams need the same contract-review methodology. What should you build?",
     options=["A subagent per team", "One skill", "An MCP server", "A shared prompt document"],
     answer="One skill",
     rationale="If multiple agents or conversations need the same expertise, that is a skill. Subagents isolate context; they do not distribute knowledge."),

dict(id="Q17", module="m7", type="mcq", difficulty=1,
     q="What is the maximum number of skills you can mount in one API container?",
     options=["3", "8", "16", "Unlimited"],
     answer="8",
     rationale="Up to eight skills per container, each pinned to a version or to `latest`."),

dict(id="Q18", module="m6", type="mcq", difficulty=2,
     q="Your skill supports markdown and LaTeX output. Where should the two templates live?",
     options=["Inline in SKILL.md so they always load", "Two files in `assets/`", "Two files in `scripts/`", "In CLAUDE.md"],
     answer="Two files in `assets/`",
     rationale="Templates in assets/ mean only the requested format is ever loaded. Inlining both costs the unused one on every invocation."),

dict(id="Q19", module="m12", type="mcq", difficulty=2,
     q="You want one skill folder to behave identically in Claude Code, Codex and Cursor. What do you restrict yourself to?",
     options=["name + description + plain markdown + relative forward-slash paths",
              "Full frontmatter including allowed-tools",
              "Only scripts, no references",
              "A single file with no subdirectories"],
     answer="name + description + plain markdown + relative forward-slash paths",
     rationale="The required pair plus plain markdown is universally supported. Extra frontmatter is silently ignored elsewhere, and `allowed-tools` is experimental."),

dict(id="Q20", module="m10", type="mcq", difficulty=3,
     q="Your skill scores 9/10 on your eval set. What does that alone tell you about the skill's value?",
     options=["It is production-ready", "Very little without a baseline run", "That its description is well tuned", "That it will generalise across models"],
     answer="Very little without a baseline run",
     rationale="Without running the same queries with the skill disabled, you have measured the model's competence rather than the skill's contribution. Value is the delta."),

# ---------- true / false ----------
dict(id="Q21", module="m1", type="tf", difficulty=1,
     q="A skill uploaded in Claude.ai is automatically available through the Claude API.",
     answer="False",
     rationale="Claude.ai/Desktop skills are a separate store from the API and Claude Code. The same folder must be installed in each."),

dict(id="Q22", module="m8", type="tf", difficulty=2,
     q="Subagents in Claude Code automatically inherit the skills available to the parent agent.",
     answer="False",
     rationale="They do not inherit skills. Skills must be attached explicitly — and a skill attached to a subagent is injected in full at dispatch, with no further progressive disclosure."),

dict(id="Q23", module="m3", type="tf", difficulty=2,
     q="Progressive disclosure applies inside a dispatched subagent exactly as it does in the main agent.",
     answer="False",
     rationale="For a skill preloaded onto a subagent, the entire SKILL.md is injected at startup. Budget for the full body, not the metadata."),

dict(id="Q24", module="m11", type="tf", difficulty=2,
     q="Instructions in a SKILL.md body can prevent an agent from writing files.",
     answer="False",
     rationale="The body is advisory text to a model. Enforcement comes from tool allow-lists, permission hooks and sandbox configuration."),

dict(id="Q25", module="m2", type="tf", difficulty=1,
     q="Unknown top-level frontmatter fields cause a skill to fail loading.",
     answer="False",
     rationale="Unknown fields are ignored for forward compatibility. Invalid YAML, wrong casing and duplicate recognised keys DO stop it loading."),

dict(id="Q26", module="m5", type="tf", difficulty=1,
     q="Claude Code ships with the document skills already installed.",
     answer="False",
     rationale="It ships with none of them. Install via the plugin marketplace, then restart."),

dict(id="Q27", module="m5", type="tf", difficulty=2,
     q="A perfectly matching description guarantees the skill will fire.",
     answer="False",
     rationale="On a trivial one-step request the model answers directly rather than consulting a skill. Triggering is also stochastic across identical requests."),

dict(id="Q28", module="m7", type="tf", difficulty=2,
     q="Files uploaded through the Files API expire automatically after a short retention window.",
     answer="False",
     rationale="They persist until explicitly deleted and count against your organisation's storage."),

dict(id="Q29", module="m4", type="tf", difficulty=2,
     q="A subagent can spawn its own subagents to parallelise further.",
     answer="False",
     rationale="Subagents have no Task tool. The topology stays a shallow tree by design."),

dict(id="Q30", module="m9", type="tf", difficulty=2,
     q="Listing a tool in a subagent's own tool list is sufficient for that subagent to use it.",
     answer="False",
     rationale="The parent's `allowed_tools` must also include it, or the subagent is denied at runtime."),

dict(id="Q31", module="m2", type="tf", difficulty=1,
     q="The folder name and the frontmatter `name` must match under the open specification.",
     answer="True",
     rationale="The name must match the parent directory name, which is why renaming a folder without updating frontmatter breaks discovery."),

dict(id="Q32", module="m12", type="tf", difficulty=2,
     q="`allowed-tools` is a reliable cross-host security control.",
     answer="False",
     rationale="It is experimental: honoured in some hosts, silently ignored in others. Never use it as the enforcement layer."),

# ---------- short answer ----------
dict(id="Q33", module="m3", type="short", difficulty=1,
     q="Name the three tiers of progressive disclosure and what loads at each.",
     answer="1) Metadata — name and description for every installed skill, always loaded (~100 tokens each). 2) Instructions — the full SKILL.md body, loaded when the description matches the request. 3) Resources — reference files, assets and scripts, loaded or executed only when the body directs it.",
     rationale="This is the single most tested concept in the course; the cost profile of each tier drives every design decision downstream."),

dict(id="Q34", module="m1", type="short", difficulty=2,
     q="Give the signature of content that belongs in `references/` rather than in the SKILL.md body, and an example from the course.",
     answer="Conditional plus bulky: material needed only in a minority of runs, and long enough to matter if it were always loaded. The course example is `references/budget_reallocation_rules.md` — most weekly runs never ask about reallocation, and the rule system is long.",
     rationale="Unconditional reference files are just a slower long SKILL.md; the saving comes from the conditionality."),

dict(id="Q35", module="m6", type="short", difficulty=2,
     q="Describe the three-part architecture used by the time-series skill and why each part sits where it does.",
     answer="Scripts for determinism (statistical tests in `diagnose.py` / `visualize.py`, so the same input produces the same numbers and only stdout costs tokens); SKILL.md for sequence (which script, in what order, what may be skipped and why, and the output tree); references for interpretation (`interpretation.md`, read only when the agent must explain what a result means).",
     rationale="This is the most transplantable pattern in the course for any analytical workflow."),

dict(id="Q36", module="m4", type="short", difficulty=2,
     q="Explain the difference between MCP and a skill using one concrete example.",
     answer="MCP provides connectivity — a BigQuery MCP server exposes tools to list tables, read a schema and run a query. The skill provides method — which table to query for weekly campaign performance, the date-range rules, the benchmarks to compare against, and the output format. MCP brings the tools; the skill knows what to do with them.",
     rationale="The course's L3 demo is exactly this: the marketing skill was edited to name the MCP server and tool while its analysis and output sections stayed unchanged."),

dict(id="Q37", module="m8", type="short", difficulty=2,
     q="How do you decide whether a convention belongs in CLAUDE.md or in a skill?",
     answer="Ask whether the rule is useful on a turn unrelated to the task. Project-wide facts — stack, architecture, file layout, universal conventions — go in CLAUDE.md, which is always in context. Rules that only apply while doing one class of work — how to add a CLI command, how to write its tests — go in a skill so they cost nothing the rest of the time.",
     rationale="Getting this split right is what keeps both files small and keeps the permanent context clean."),

dict(id="Q38", module="m10", type="short", difficulty=3,
     q="Outline a minimum credible evaluation for a new skill.",
     answer="Define should-fire and should-not-fire queries; run each at least three times because triggering is stochastic; write objectively checkable behavioural assertions (file exists at path, all required sections present, steps executed in the specified order); run the same set with the skill disabled as a baseline; record pass rate, tokens and duration as means with standard deviations; hold back part of the set if you are tuning the description; finish with human review and a pass on every model you deploy on.",
     rationale="Trigger reliability, behaviour and cost are three separate failure modes, and only the delta over baseline demonstrates value."),

dict(id="Q39", module="m11", type="short", difficulty=2,
     q="What must a pre-install security audit of a third-party skill cover, and what is the top red flag?",
     answer="The whole folder: SKILL.md end to end, every file in `scripts/` (what it executes, writes and sends), every reference file, and the assets. The top red flag is a skill that fetches an external URL and then acts on what it finds — that delegates the skill's contents to whoever controls the URL, as a mutable, unversioned dependency inside a trusted path.",
     rationale="Reviewing only SKILL.md inspects the least dangerous file in the folder."),

dict(id="Q40", module="m5", type="short", difficulty=2,
     q="Why should skill descriptions be slightly 'pushy', and what is the limit of that technique?",
     answer="Models systematically under-trigger skills, so explicit 'use this whenever the user mentions X, Y or Z' language measurably improves firing. The limit is that no description will fire on a trivial one-step request — the model just answers directly — and over-broad descriptions start hijacking unrelated requests, which is why should-not-fire eval cases matter.",
     rationale="Description tuning is a two-sided problem: under-triggering and over-triggering are both failures."),

dict(id="Q41", module="m7", type="short", difficulty=2,
     q="List the five parts of a Messages API request that uses a custom skill.",
     answer="1) The model. 2) The beta headers (historically skills, code-execution and files-api; the skills header is now optional post-GA). 3) `container={\"skills\": [...]}` naming each skill by type, skill_id and version. 4) `tools` including the code execution tool. 5) Messages referencing uploaded inputs by file_id via a container_upload block.",
     rationale="Omitting the code execution tool produces a 400 rather than a degraded answer."),

dict(id="Q42", module="m2", type="short", difficulty=1,
     q="Name the three conventional skill subdirectories and what each holds.",
     answer="`scripts/` — code to execute, where only the output enters context. `references/` — documents read on demand, costing their length at read time. `assets/` — templates, logos, schemas and data files used in output rather than read as instructions.",
     rationale="Each directory maps to a different loading mechanic, so the filing decision is really a token-budgeting decision."),

# ---------- applied / judgement ----------
dict(id="Q43", module="m6", type="applied", difficulty=3,
     q="A compliance team wants every client report to place the disclaimer on page two, use one specific blue, and follow a fixed section order. A marketing team wants help generating visually varied campaign concepts. How should the degrees-of-freedom dial differ between these two skills, and what does that look like concretely?",
     answer="Compliance gets low freedom: an explicit, ordered sequence, exact hex values, a fixed section list, a named output template in `assets/`, and explicit statements of when a step may be skipped and why. Deviation is a defect. Marketing gets high freedom: the skill states goals, constraints and a palette range rather than a sequence, and deliberately leaves style, layout and colour selection to the model — with the skill supplying brand guardrails rather than a script.",
     rationale="The dial is set by whether variation is a defect or the point. Getting this backwards produces either non-compliant reports or monotonous creative output."),

dict(id="Q44", module="m8", type="applied", difficulty=3,
     q="Interactively testing a CLI is filling your main context with repeated run transcripts. Design a fix using the course's primitives, and state what each piece buys you.",
     answer="Create a test-generation skill carrying your fixture and assertion conventions, and a review skill carrying the convention checklist. Attach each to its own subagent: the reviewer with read-only tools (Read, Grep, Glob, Bash) so it reports rather than fixes; the test runner additionally with Edit and Write since it must create test files. Dispatch both from the parent, which stays on development and receives only verdicts and diffs. The skills buy consistency of method; the subagents buy context isolation and parallelism; the restricted tool lists buy enforcement.",
     rationale="This is the L6 architecture. The read-only reviewer is the detail people skip, and it is what keeps your true error rate visible."),

dict(id="Q45", module="m13", type="applied", difficulty=3,
     q="You run a recurring multi-check verification pass over batches of records. Sketch the skill structure and say what stays out of the SKILL.md.",
     answer="`scripts/` takes the deterministic work — schema and permitted-value validation, the mechanical checks, and summarisation into a fixed results tree. `references/` takes the methodology and per-flag decision rules, read only when a case needs adjudicating. `assets/` takes the column contract and remark templates. SKILL.md keeps only the sequence, the skip conditions with reasons, and the output contract naming every file the run must produce. Out of SKILL.md: the rulebook itself, the statistical detail, the templates, and anything that changes independently of the workflow order.",
     rationale="Named, reproducible output paths are what make a run auditable months later; a short body is what keeps the skill maintainable."),

dict(id="Q46", module="m4", type="applied", difficulty=3,
     q="A colleague proposes building one large agent with fifteen MCP servers connected so it 'can do anything'. What is wrong with this on context grounds, and what would you propose instead?",
     answer="MCP tool definitions sit in the context window permanently, so fifteen servers can consume a significant share of the window before the user types anything — raising cost and increasing degradation risk on every turn, including turns that use none of them. Instead: connect only the servers the workflow actually needs; move rarely used capabilities into skills whose scripts are invoked on demand, so their cost is paid only when they fire; and push noisy or independent work into subagents with narrow tool lists so their transcripts never reach the main window.",
     rationale="The distinguishing question between these primitives is what each costs when it is NOT being used."),

dict(id="Q47", module="m9", type="applied", difficulty=3,
     q="You are shipping an Agent SDK application that grants Write and Bash. What must you add before it is safe to run unattended, and why is the course demo not a template for this?",
     answer="A permission layer: a runtime permission callback or an appropriate permission mode, plus hooks to gate or audit destructive actions, and a tool allow-list reduced to the minimum each agent actually needs. The demo deliberately grants Write and Bash without confirmation because it runs in a sandbox under supervision — Claude Code's interactive approval prompts and interrupts are a feature you must rebuild when you leave Claude Code, not something the SDK provides by default.",
     rationale="The course states this explicitly as the next step; treating the demo's permissions as production-ready is the mistake it warns against."),

dict(id="Q48", module="m12", type="applied", difficulty=3,
     q="You are teaching this course material internally in six months. Which two technical claims most need re-verification before you present them, and why?",
     answer="First, the API surface: the beta headers and the code-execution tool version string. The Skills API has already gone GA, making its header optional, and newer code-execution tool versions exist — so the exact strings should be shown as dated examples with a note to check current docs. Second, subagent skill injection: the `skills:` frontmatter field is documented to preload full skill content, but there are open reports of it not behaving that way while filesystem-capable subagents can often discover skills themselves. Present the documented behaviour, flag the caveat, and tell learners to verify in their own version.",
     rationale="Both are places where the recorded course is a point-in-time simplification of a fast-moving surface."),

dict(id="Q49", module="m1", type="applied", difficulty=2,
     q="A colleague says 'we already have a great prompt for this in a shared doc — a skill would be over-engineering'. When are they right, and when are they wrong?",
     answer="They are right when the workflow runs rarely, or when its conventions are still being argued about — a skill then adds a folder to own, a convention to keep current and a version to pin, for no repeatability gain. They are wrong once the workflow recurs on a settled convention, because at that point the prompt is costing repetition, depends on tacit knowledge the operator may lack, pollutes context with pasted specifications, and cannot be reviewed, versioned or distributed. The threshold is repetition plus a settled convention, not complexity.",
     rationale="Both over- and under-adoption are real failure modes; naming the threshold prevents each."),

dict(id="Q50", module="m10", type="applied", difficulty=3,
     q="Your skill's trigger rate is 60% on queries that should fire it. Give three distinct changes you would try, in order, and how you would avoid fooling yourself.",
     answer="1) Rewrite the description to state what it does AND when to use it, in the third person, with the literal keywords users type — and make it slightly pushy, since under-triggering is the dominant failure. 2) Check for collisions: near-identical descriptions or overlapping scopes across the library degrade routing, so sharpen the distinct scope. 3) Check whether the failing queries are trivial one-step requests, which the model will answer directly regardless of description quality — if so, the queries are the problem, not the skill. To avoid fooling yourself: run each query at least three times because triggering is stochastic, keep should-not-fire cases in the set so you detect over-triggering, and tune on a training split while selecting on held-out queries.",
     rationale="This is exactly what skill-creator's description-optimisation loop automates: repeats for stability, a 60/40 split, and selection on the held-out set."),
# ---------- added from the condensed course write-up ----------
dict(id="Q51", module="m2", type="short", difficulty=2,
     q="A skill's frontmatter can declare an `allowed-tools` list. Explain what that achieves and what it does not.",
     answer="It scopes which tools the agent may use while that skill is active, so a skill acts as both a capability unlock — bringing in scripts and knowledge — and a capability limiter. Restricting a spreadsheet-reformatting skill to file read and write, while denying shell and network, makes its behaviour more constrained and auditable. What it does not achieve is a guarantee: the field is optional and experimental, honoured in some hosts and silently ignored in others, so the actual enforcement still rests with the harness's own tool permissions.",
     rationale="Both halves matter. Dismissing the field entirely misses a real design lever; treating it as enforcement is how a shared skill ends up with more reach than anyone intended."),

dict(id="Q52", module="m3", type="mcq", difficulty=2,
     q="Some environments now let a tool be marked 'deferred'. What does that do?",
     options=["Only the tool's name is visible up front; its full schema is pulled in on demand before use",
              "The tool runs inside a subagent so its output stays out of the main window",
              "The tool is disabled until a skill explicitly requests permission for it",
              "The tool's JSON schema is compressed to about half its token cost"],
     answer="Only the tool's name is visible up front; its full schema is pulled in on demand before use",
     rationale="It is progressive disclosure applied to tools. Tool definitions traditionally sat in context for the whole conversation, which is the asymmetry that made skills cheaper; deferring narrows that gap."),

dict(id="Q53", module="m4", type="tf", difficulty=2,
     q="A skill persists across conversations, while a subagent can persist state across sessions between itself and the parent agent.",
     answer="True",
     rationale="Two different kinds of continuity. The skill's persistence is what distributes expertise to everyone; the subagent's is a working relationship with its parent."),

dict(id="Q54", module="m4", type="mcq", difficulty=3,
     q="A colleague wants to add skills to an in-house agent with a model, a chat loop and HTTP tools, but no filesystem and no shell. What is true?",
     options=["Skills cannot work there yet — reading skill folders and running bundled scripts is done by filesystem and execution tools",
              "Skills will work, because the Skill tool brings its own file access",
              "Skills will work for instructions, but bundled scripts must be rewritten as HTTP tools",
              "Skills will work if the folders are pasted into the system prompt instead of read from disk"],
     answer="Skills cannot work there yet — reading skill folders and running bundled scripts is done by filesystem and execution tools",
     rationale="Tools are what power the ability to generate, read and load skills in the first place. Filesystem plus an execution tool is the floor, not an optimisation."),

dict(id="Q55", module="m5", type="short", difficulty=2,
     q="Put the skill-creator pipeline in order and say why validation sits where it does.",
     answer="Skill idea and examples, then `init_skill.py` scaffolds SKILL.md and the folder structure, then a package script zips it into a bundle, then a validate script checks SKILL.md and its frontmatter, and the result is installed for future chats. Validation comes after packaging because there is nothing to validate until the files exist — it checks the built artefact, not the intention.",
     rationale="Validating early feels like good practice and is the common wrong answer. The check is on structure and frontmatter, which only exist once scaffolding has run."),

dict(id="Q56", module="m7", type="mcq", difficulty=2,
     q="How does a file get into the API execution container, and a generated file back out?",
     options=["Upload through the Files API, reference it in the message with a container_upload block, and download the output by its file ID",
              "Attach it to the message and read the result from the response text",
              "Place it in the skill's assets/ folder, which synchronises with the container both ways",
              "Mount a local directory, since the code execution tool exposes the host filesystem"],
     answer="Upload through the Files API, reference it in the message with a container_upload block, and download the output by its file ID",
     rationale="Mailbox in, mailbox out. assets/ does travel into the container with the skill, but one way and fixed at upload — it is not a channel for run outputs."),

dict(id="Q57", module="m7", type="tf", difficulty=2,
     q="The container behind Claude AI and Desktop can reach the internet and install a package mid-task, while the API code-execution container cannot.",
     answer="True",
     rationale="This is the single most common cause of a script that passes in the desktop app and fails on the API. The API image is fixed — pandas, numpy, scipy, matplotlib, python-docx, python-pptx, pypdf and similar — with no runtime installation."),

dict(id="Q58", module="m8", type="short", difficulty=2,
     q="State the rule of thumb for choosing between CLAUDE.md and a skill, and give one example each way.",
     answer="If it needs to be everywhere, it goes in CLAUDE.md; if it is only relevant to one repeatable job, make it a skill. CLAUDE.md is always in context, every conversation, so it carries things true of the whole project — tech stack, architecture, where files live. A skill carries the conventions for one recurring task, such as how a CLI command is added, and loads only when that task comes up.",
     rationale="Getting this split right is what keeps both files small. The test is whether the rule is useful on a turn unrelated to the task."),

dict(id="Q59", module="m9", type="applied", difficulty=3,
     q="In the research agent, the learning-a-tool skill is attached to the orchestrator and to none of the three subagents. Explain why that is deliberate rather than an oversight.",
     answer="The skill's content is workflow: which subagent researches what, how the three research streams are folded into progressive levels through a separate reference file, and the fixed output structure. That is the orchestrator's job. The subagents need scoped tools and a clear brief, not the plan for assembling the result. There is also a cost dimension: a skill attached to a subagent is preloaded in full at dispatch with no progressive disclosure, so putting an orchestration skill on three researchers would pay for the whole body three times and give each of them instructions they have no use for.",
     rationale="This is the distinction between an orchestration skill and a task skill, and it is the clearest illustration in the course of matching the skill to the agent that actually needs it."),

dict(id="Q60", module="m4", type="applied", difficulty=3,
     q="A team connects an MCP server to their warehouse, the agent can query it, and results still differ between analysts. Diagnose this in the course's own terms and say what to build.",
     answer="MCP delivered the ingredients — access to the data and the tools to query it — but nothing yet encodes the recipe: the repeatable steps that turn that data into the output you actually want. Access without method produces exactly this variance. The fix is a skill carrying the procedure: which tables and date ranges, the metrics and benchmarks, the decision rules, and a fixed output structure, so any analyst on any conversation gets the same shape of answer.",
     rationale="Variance is inherent to a non-deterministic model, which is the reason to write explicit steps rather than a reason to accept it. Adding more connectivity never fixes a missing method."),
# ---------- Claude Code workflow additions, matching the SKL domain of the timed paper ----------
dict(id="Q61", module="m8", type="mcq", difficulty=2,
     q="A team needs a validation script to run every time someone edits a CSV, regardless of what Claude happens to be reasoning about. Which mechanism fits?",
     options=["A hook tied to the file-edit event, since hooks fire deterministically rather than by the model's judgement",
              "A skill whose description mentions CSV validation, so Claude pattern-matches the file type",
              "A line in CLAUDE.md instructing Claude to always validate CSVs",
              "A subagent dedicated to validation, dispatched whenever a CSV appears"],
     answer="A hook tied to the file-edit event, since hooks fire deterministically rather than by the model's judgement",
     rationale="The requirement is 'no matter what Claude is thinking', which rules out anything the model has to choose to do. A skill and a CLAUDE.md instruction both depend on judgement; a hook is event-driven."),

dict(id="Q62", module="m8", type="tf", difficulty=3,
     q="When a skill name exists at both personal and project level, the project version wins because it is more specific to the work.",
     answer="False",
     rationale="Precedence runs enterprise, then personal, then project — so a personal skill overrides the repository's. This catches almost everyone out, and it means a project skill cannot enforce anything mandatory on its own."),

dict(id="Q63", module="m5", type="mcq", difficulty=2,
     q="A plugin bundles a skill called deploy and your repository already has its own deploy skill. Both stay usable. Why?",
     options=["Plugin skills are namespaced as plugin-name:skill-name, so they never collide with personal or project skills",
              "Claude appends a numeric suffix to whichever was installed second",
              "The plugin's version loads only when the project has no skill of that name",
              "Claude prompts the user to choose each time either is triggered"],
     answer="Plugin skills are namespaced as plugin-name:skill-name, so they never collide with personal or project skills",
     rationale="Namespacing removes the conflict rather than resolving it, which is why a plugin's /my-kit:deploy and your /deploy coexist. Same-scope conflicts are the case where precedence has to pick a winner."),

dict(id="Q64", module="m11", type="applied", difficulty=3,
     q="A skill performs an irreversible publish to a downstream consumer. It occasionally fires when someone was only asking a question about publishing. Give the right fix and say why description tuning is not enough.",
     answer="Set `disable-model-invocation` on the skill so it can only be run deliberately by name. Auto-invocation is a convenience that should be switched off for destructive or irreversible work. Narrowing the description is the correct move for ordinary over-triggering, but it only reduces the rate — and for an action that cannot be undone the acceptable rate is zero, which only manual invocation guarantees. A confirmation line in the body is advisory text, not a control.",
     rationale="This is the clearest case where the usual routing advice is the wrong tool. The question is not how often it misfires but whether a misfire is survivable."),

dict(id="Q65", module="m12", type="short", difficulty=2,
     q="Twelve repositories across three teams need the same data-quality skills kept in step. Copying `.claude/skills` into each has already drifted. What is the recommended route, and why do the obvious alternatives fail?",
     answer="Package them as a plugin and distribute through a marketplace, so each repository installs a versioned copy and updates propagate. Project skills reach only the repository they sit in, which is what caused the drift. Personal skills do apply across all a person's projects, but that multiplies copies rather than removing them and nothing keeps twelve home directories in step. Referencing a canonical repo by relative path breaks as soon as the checkout layout differs.",
     rationale="Plugins plus a marketplace are the documented answer for sharing skills across teams and projects with versioning. The distinction to hold is scope versus distribution: personal skills widen scope, plugins solve distribution."),
]
